### ISSUE TITLE
Support for local dependencies

### ISSUE THREAD

**Issue by david1542** [langchain-ai/langgraph-studio#161]
Hi everyone :)

We have a monorepo with a LangGraph project. The LangGraph project consumes local packages from within the monorepo.
When I tried to use LangGraph studio, the docker build failed because pip doesn't know the local packages (I assume they are not copied to the Docker build process.

I tried to symlink stuff into the project/creating a separate toml file for the symlinks but that didn't work either.

My toml file basically looks like this

```toml
[tool.poetry]
name = "some-service"
version = "0.1.0"
description = ""
packages = [{ include = "*", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10.5,<3.12"
package-a = { path = "../../packages/a_package", develop = true }
package-b = { path = "../../packages/b_package", develop = true }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
